[pytest]
testpaths = tests
addopts =
    --base-url https://www.saucedemo.com
    --screenshot only-on-failure
    --video retain-on-failure
    --tracing retain-on-failure
    --alluredir=allure-results
    --html=reports/report.html
    --self-contained-html
    -v
    --junitxml=reports/junit-report.xml
    --reruns 1
    --reruns-delay 2

markers =
    smoke: marks tests as smoke tests
    regression: marks tests as regression tests
    login: marks tests as login tests
    cart: marks tests as cart tests
    checkout: marks tests as checkout tests
    inventory: marks tests as inventory tests
