[pytest]
testpaths = tests
addopts = --html=reports/report.html --self-contained-html --alluredir=reports/allure -v
markers =
    smoke: marks tests as smoke tests
    regression: marks tests as regression tests
    login: marks tests as login tests
    cart: marks tests as cart tests
    checkout: marks tests as checkout tests
    inventory: marks tests as inventory tests
